kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-pme-configmap
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
data:
  JDBC_DRIVER: {{ .Values.pme.jdbc.driver | quote }}
  JDBC_URL: {{ .Values.pme.jdbc.url | quote }}
