{{ if .Values.azure.secretFromKeyvault }}
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name }}-pme-keyvault
spec:
  provider: azure
  secretObjects:
  - data:
    - key: JDBC_USER
      objectName: PME-DB-USER
    - key: JDBC_PASSWORD
      objectName: PME-DB-PASSWORD
    secretName: {{ .Release.Name }}-pme-secret
    type: Opaque
  parameters:
    usePodIdentity: "false"
    keyvaultName: {{ .Values.azure.keyvaultName | quote }}
    objects:  |
      array:
        - |
          objectName: PME-DB-USER
          objectType: secret
          objectVersion: ""
        - |
          objectName: PME-DB-PASSWORD
          objectType: secret
          objectVersion: ""
    resourceGroup: {{ .Values.azure.resourceGroup | quote }}
    subscriptionId: {{ .Values.azure.subscriptionId | quote }}
    tenantId: {{ .Values.azure.tenantId | quote }}
{{ end }}
