{{ if not .Values.azure.secretFromKeyvault }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-pme-secret
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
type: Opa
data:
  JDBC_USER: {{ .Values.pme.jdbc.user | b64enc }}
  JDBC_PASSWORD: {{ .Values.pme.jdbc.password | b64enc }}
{{ end }}
