apiVersion: v1
kind: Service
metadata: {{ $fullname := printf "%s-pme-deployment" .Release.Name | trunc 63 | trimSuffix "-" }}
  name: {{ .Release.Name }}-pme-service
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: {{ $fullname }}
